# このNotebookは、モジュール内で作成したもののTestようである

In [3]:
from kazustat import GMMfunction
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import make_moons
from scipy.stats import gaussian_kde

In [ ]:
data = np.array([1, 1.5, 2, 6, 6.5, 7])
datab = np.array([1, 1, 2.5, 7.5, 4.3, 9])
df = pd.DataFrame(data)
kde_func = gaussian_kde(data)

In [18]:
kde_func

x_range = np.linspace(data.min(), data.max(), 100)
kde_array = kde_func(x_range)

In [20]:
data_P = np.array([1, 1.5, 2])
data_Q = np.array([6, 6.5, 7])

# 1. KDE関数を定義
kde_P = gaussian_kde(data_P)
kde_Q = gaussian_kde(data_Q)

# 2. 評価点を定義
x_range = np.linspace(0, 10, 1000)

# 3. 各評価点での密度を計算
density_P = kde_P(x_range)
density_Q = kde_Q(x_range)

# 4. 差分を計算
# この差分がゼロになる点が交点
difference = density_P - density_Q

In [21]:
difference

array([ 1.51791053e-02,  1.61575740e-02,  1.71887673e-02,  1.82747806e-02,
        1.94177431e-02,  2.06198146e-02,  2.18831824e-02,  2.32100578e-02,
        2.46026731e-02,  2.60632770e-02,  2.75941310e-02,  2.91975052e-02,
        3.08756732e-02,  3.26309076e-02,  3.44654752e-02,  3.63816311e-02,
        3.83816138e-02,  4.04676394e-02,  4.26418955e-02,  4.49065352e-02,
        4.72636711e-02,  4.97153685e-02,  5.22636394e-02,  5.49104354e-02,
        5.76576412e-02,  6.05070677e-02,  6.34604452e-02,  6.65194164e-02,
        6.96855295e-02,  7.29602315e-02,  7.63448611e-02,  7.98406420e-02,
        8.34486761e-02,  8.71699373e-02,  9.10052647e-02,  9.49553566e-02,
        9.90207643e-02,  1.03201887e-01,  1.07498964e-01,  1.11912074e-01,
        1.16441126e-01,  1.21085856e-01,  1.25845823e-01,  1.30720407e-01,
        1.35708803e-01,  1.40810019e-01,  1.46022875e-01,  1.51345999e-01,
        1.56777829e-01,  1.62316607e-01,  1.67960385e-01,  1.73707020e-01,
        1.79554178e-01,  

In [22]:
len(difference)

1000

In [38]:
a = df[0].to_numpy().T
a

array([1. , 1.5, 2. , 6. , 6.5, 7. ])

In [37]:
data_P

array([1. , 1.5, 2. , 2.5])

In [29]:
from scipy.stats import gaussian_kde
from scipy.optimize import brentq
import numpy as np

# ダミーデータ
data_P = np.array([1, 1.5, 2, 2.5])
data_Q = np.array([4, 4.5, 5, 5.5])

# 1. KDE関数の定義
kde_P = gaussian_kde(data_P)
kde_Q = gaussian_kde(data_Q)

# 2. 差分関数の定義
def difference_function(x):
    """P(x) - Q(x) を計算する関数"""
    return kde_P(x) - kde_Q(x)

# 3. 交点が存在する区間を特定 (例: 2.5 から 4.5 の間にあると推定)
# 注: brentq を使うには、区間の両端で関数の符号が異なっている必要があります
try:
    # 4. 求根アルゴリズムで正確な交点 X を計算
    # 探索範囲 [a, b] を指定
    intersection_x = brentq(difference_function, 2.5, 4.5)
    
    # 交点でのY値も取得
    intersection_y = kde_P(intersection_x)[0]

    print(f"✅ 数値計算による正確な交点座標:")
    print(f"X = {intersection_x:.4f}, Y = {intersection_y:.4f}")

except ValueError:
    print("❌ 指定された区間で符号の変化が見られませんでした。探索範囲を見直してください。")

✅ 数値計算による正確な交点座標:
X = 3.2500, Y = 0.0711


In [30]:
kde_P

## 検定方法などの検証

In [39]:
from kazustat import continuous

In [41]:
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [5, 4, 3, 2, 1]
})

In [44]:
Continuous = continuous.Continuous(df)
Continuous.check_normalitiy('A')

DataFrame (shape=(5, 2)) has been set


(True, 0.9671738743782043)